site:
  title: Weather Routing
  url:  https://nowhere.net
  start_page: weather_routing::index.adoc
 
content:
  sources:
    - url: ..
      start_path: manual
      branches: HEAD
      edit_url: https://github.com/opencpn-manuals/weather_routing_pi/edit/master/{path}

ui:   
  bundle:
    url: https://gitlab.com/leamas/antora-ui-default/-/raw/master/latest/ui-bundle.zip
    snapshot: true

output:
  dir: ./docs
  clean: true              
